apiVersion: v1
kind: Service:
metadata:
  name: globetrotter-service
  namespace: gt-weather
  labels:
    app: globetrot-weather
spec:
  selector:
    app: globetrot-weather
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30033
#testing
